### ISSUE TITLE
Implement some type of use metrics in CKAN and on the CKAN_data directories

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/data-distribution#7]

**Comment by brucecrevensten** [comment]
This is likely a one-two punch.  On CKAN itself, we'd use the [Google Analytics](https://github.com/ckan/ckanext-googleanalytics) plugin.  On CKAN_data, I think [awstats](http://www.awstats.org) is the way to go.

**Comment by BobTorgerson** [comment]
We have both of these metrics in use now. AWStats is available at: http://data.snap.uaf.edu/awstats/awstats.pl  and Google Analytics is hooked up to the CKAN instance and can be viewed in our Google Analytics page.
